# Generated by Django 6.0.4 on 2026-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_persistent',
            field=models.BooleanField(default=False),
        ),
    ]
