# Generated by Django 6.0.4 on 2026-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
