# Generated by Django 6.0.4 on 2026-05-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_task_estimated_distance_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('LOST', 'Lost'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='customers.driverprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='customers.task')),
            ],
            options={
                'indexes': [models.Index(fields=['task', 'outcome'], name='customers_t_task_id_571e3b_idx'), models.Index(fields=['driver', 'outcome'], name='customers_t_driver__f44c88_idx')],
                'unique_together': {('task', 'driver')},
            },
        ),
    ]
