# Generated by Django 5.2.13 on 2026-05-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_task_estimated_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='face_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle'), ('CAR', 'Car'), ('MINI_TRUCK', 'Mini Truck'), ('ON_FOOT', 'On Foot')], max_length=20),
        ),
    ]
