# Generated by Django 6.0.4 on 2026-05-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_taskassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='debt_limit',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('PRICE_UPDATE', 'Price Update'), ('TASK_COMPLETED', 'Task Completed'), ('PAYMENT_REQUIRED', 'Payment Required'), ('SYSTEM_ALERT', 'System Alert'), ('TASK_OFFER', 'Task Offer')], max_length=20),
        ),
    ]
