# Generated by Django 6.0.4 on 2026-05-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_driverprofile_debt_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_return_trip',
            field=models.BooleanField(default=False),
        ),
    ]
