# Generated by Django 5.2.13 on 2026-05-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_driverprofile_debt_limit_and_more'),
        ('customers', '0006_driverprofile_rejection_reason_driverprofile_status'),
    ]

    operations = [
    ]
