# Generated by Django 6.0.4 on 2026-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_merge_20260510_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskproof',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
    ]
