# Generated by Django 5.2.13 on 2026-05-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_merge_20260510_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_return_trip',
            field=models.BooleanField(default=False),
        ),
    ]
