# Generated by Django 6.0.4 on 2026-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_taskproof_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_return_trip',
            field=models.BooleanField(default=False),
        ),
    ]
