# Generated by Django 6.0.4 on 2026-05-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_task_is_return_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_duration_minutes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
    ]
