# Generated by Django 5.2.13 on 2026-05-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_task_is_return_trip'),
        ('customers', '0009_task_is_return_trip'),
    ]

    operations = [
    ]
