# Generated by Django 6.0.4 on 2026-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_task_estimated_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle'), ('CAR', 'Car'), ('MINI_TRUCK', 'Mini Truck'), ('ON_FOOT', 'On Foot')], max_length=20, null=True),
        ),
    ]
