# Generated by Django 5.2.13 on 2026-05-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_merge_20260526_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dropoff_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='pickup_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
