# Generated by Django 5.2.13 on 2026-05-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_add_pickup_dropoff_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='item_size',
            field=models.CharField(blank=True, choices=[('up_to_2kg', 'Up to 2kg'), ('up_to_6kg', 'Up to 6kg'), ('up_to_10kg', 'Up to 10kg')], max_length=10, null=True),
        ),
    ]
