# Generated by Django 6.0.4 on 2026-05-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_task_vehicle_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
