# Generated by Django 5.2.13 on 2026-05-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_add_item_size_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
    ]
