# Generated by Django 5.2.13 on 2026-05-28 08:42

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_add_priority_to_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('ARRIVED', 'Arrived'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('PURCHASED', 'Purchased'), ('DELIVERING', 'Delivering'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
