# Generated by Django 5.2.13 on 2026-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_add_awaiting_payment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('COMMISSION', 'Commission'), ('EARNING', 'Earning'), ('DRIVER_PAYMENT', 'Driver Payment')], max_length=20),
        ),
    ]
