# Generated by Django 5.2.13 on 2026-05-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_commissionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
