# Generated by Django 5.2.13 on 2026-06-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_alter_commissionpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproof',
            name='ocr_failed',
            field=models.BooleanField(default=False),
        ),
    ]
