# Generated by Django 5.2.13 on 2026-06-01 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_taskproof_ocr_failed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('PRICE_UPDATE', 'Price Update'), ('TASK_COMPLETED', 'Task Completed'), ('PAYMENT_REQUIRED', 'Payment Required'), ('SYSTEM_ALERT', 'System Alert'), ('TASK_OFFER', 'Task Offer')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.user')),
            ],
        ),
    ]
