# Generated by Django 5.2.13 on 2026-06-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_add_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_dispatch_exhausted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='dispatch_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
