# Generated by Django 5.2.13 on 2026-06-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_auto_cancel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='arrived_at_dropoff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
