# Generated by Django 6.0.4 on 2026-07-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_delete_notification'),
        ('customers', '0019_add_notification'),
        ('customers', '0021_arrived_at_dropoff_at'),
    ]

    operations = [
    ]
